In [1]:
import numpy as np

In [2]:
a=[5,6,3,8,7,86,96]
arr=np.array(a)
print(a)


[5, 6, 3, 8, 7, 86, 96]


In [3]:
print(arr[3])
print(arr[5])

8
86


In [4]:
aa=[[1,86,96,7],[5,8,7,9]]
A=np.array(aa)
print(A)

[[ 1 86 96  7]
 [ 5  8  7  9]]


In [5]:
A=np.array([[1,86,96,7],[5,8,7,9]])
print(A)

[[ 1 86 96  7]
 [ 5  8  7  9]]


In [6]:
print(type(A))

<class 'numpy.ndarray'>


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
np.ndim(arr)

1

In [9]:
np.ndim(A)

2

In [10]:
print(np.size(arr))

7


In [11]:
print(np.size(A))

8


In [12]:
print(np.shape(arr))

(7,)


In [13]:
print(np.shape(A))

(2, 4)


In [14]:
A=np.array([[1,5,3],[7,8,9],[4,6,2]])
print(A)

[[1 5 3]
 [7 8 9]
 [4 6 2]]


In [15]:
print(A[0,:])
print(A[1,:])
print(A[2,:])


[1 5 3]
[7 8 9]
[4 6 2]


In [16]:
print(A[:,0])
print(A[:,1])
print(A[:,2])

[1 7 4]
[5 8 6]
[3 9 2]


In [17]:
print(A[2,1])

6


In [18]:
import pandas as pd

In [19]:
Dataset = {
    "state": ['Andhra pradesh', 'Maharasthra', 'karnakata', 'kerla'],
    "capital": ['Hyderabad', 'mumbai', 'bengaluru', 'Trivandrum'],
    "Literacy %": [89, 45, 63, 87],
    "Avg High Temp(c)": [33, 30, 29, 31]
}
print(Dataset)
df = pd.DataFrame(Dataset)
print(df)

{'state': ['Andhra pradesh', 'Maharasthra', 'karnakata', 'kerla'], 'capital': ['Hyderabad', 'mumbai', 'bengaluru', 'Trivandrum'], 'Literacy %': [89, 45, 63, 87], 'Avg High Temp(c)': [33, 30, 29, 31]}
            state     capital  Literacy %  Avg High Temp(c)
0  Andhra pradesh   Hyderabad          89                33
1     Maharasthra      mumbai          45                30
2       karnakata   bengaluru          63                29
3           kerla  Trivandrum          87                31


In [20]:
df = pd.DataFrame({
    "state": ['Andhra pradesh', 'Maharasthra', 'karnakata', 'kerla'],
    "capital": ['Hyderabad', 'mumbai', 'bengaluru', 'Trivandrum'],
    "Literacy %": [89, 45, 63, 87],
    "Avg High Temp(c)": [33, 30, 29, 31]
})
print(df)

            state     capital  Literacy %  Avg High Temp(c)
0  Andhra pradesh   Hyderabad          89                33
1     Maharasthra      mumbai          45                30
2       karnakata   bengaluru          63                29
3           kerla  Trivandrum          87                31


In [21]:
print(df.head(2))

            state    capital  Literacy %  Avg High Temp(c)
0  Andhra pradesh  Hyderabad          89                33
1     Maharasthra     mumbai          45                30


In [22]:
print (df.tail(2))

       state     capital  Literacy %  Avg High Temp(c)
2  karnakata   bengaluru          63                29
3      kerla  Trivandrum          87                31


In [23]:
print(df.dtypes)

state               object
capital             object
Literacy %           int64
Avg High Temp(c)     int64
dtype: object


In [24]:
print(df.sort_values("Literacy %", ascending=False))

            state     capital  Literacy %  Avg High Temp(c)
0  Andhra pradesh   Hyderabad          89                33
3           kerla  Trivandrum          87                31
2       karnakata   bengaluru          63                29
1     Maharasthra      mumbai          45                30


In [25]:
print(df[['capital']])

      capital
0   Hyderabad
1      mumbai
2   bengaluru
3  Trivandrum


In [26]:
print(df[['state', 'capital']])

            state     capital
0  Andhra pradesh   Hyderabad
1     Maharasthra      mumbai
2       karnakata   bengaluru
3           kerla  Trivandrum


In [27]:
print(df.loc[2])

state               karnakata
capital             bengaluru
Literacy %                 63
Avg High Temp(c)           29
Name: 2, dtype: object


In [28]:
print(df.iloc[2])

state               karnakata
capital             bengaluru
Literacy %                 63
Avg High Temp(c)           29
Name: 2, dtype: object


In [29]:
print(df.iloc[1,3])

30


In [31]:
print(df.loc[1,'Literacy %'])

45


In [35]:
a={"Distance": [15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16, 17, 14]}

In [36]:
import pandas as pd
df=pd.DataFrame(a)
print(df)

print("The number of element in the the column is ='",df['Distance'].size)

    Distance
0         15
1         13
2         16
3         16
4         15
5         16
6         17
7         14
8         15
9         16
10        16
11        17
12        14
The number of element in the the column is =' 13


In [37]:
df2=pd.crosstab(index=df['Distance'],columns='Frequency')
print(df2)


col_0     Frequency
Distance           
13                1
14                2
15                3
16                5
17                2


In [38]:
print(df2['Frequency'].sum())


13


In [39]:
df2['Relative_Frequencies']=df2['Frequency']/df2['Frequency'].sum()
df2['Percentage']=df2['Frequency']/df2['Frequency'].sum()*100
print(df2)


col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
13                1              0.076923    7.692308
14                2              0.153846   15.384615
15                3              0.230769   23.076923
16                5              0.384615   38.461538
17                2              0.153846   15.384615


In [40]:
df2.loc['Total']=df2.sum()
print(df2)


col_0     Frequency  Relative_Frequencies  Percentage
Distance                                             
13              1.0              0.076923    7.692308
14              2.0              0.153846   15.384615
15              3.0              0.230769   23.076923
16              5.0              0.384615   38.461538
17              2.0              0.153846   15.384615
Total          13.0              1.000000  100.000000


In [41]:
import numpy as np
import pandas as pd

In [42]:
data=[328, 470, 405, 375, 298, 326, 276, 362, 410, 255, 391, 370, 455, 229, 300, 183,
 283, 366, 400, 495, 215, 157, 374, 306, 280, 409, 321, 269, 398, 200]
diction={"Score":data}
df=pd.DataFrame(diction)
print(df)


    Score
0     328
1     470
2     405
3     375
4     298
5     326
6     276
7     362
8     410
9     255
10    391
11    370
12    455
13    229
14    300
15    183
16    283
17    366
18    400
19    495
20    215
21    157
22    374
23    306
24    280
25    409
26    321
27    269
28    398
29    200


In [43]:
A=min(data)
print('The lowest value is ',A)
B=max(data)
print('The highestest value is ',B)
N=round((B-A)/50)
N


The lowest value is  157
The highestest value is  495


7

In [44]:
bins=np.linspace(150,500,N+1)
print(bins)

[150. 200. 250. 300. 350. 400. 450. 500.]


In [45]:
df['Class Intervals']=pd.cut(df['Score'],bins=bins,right=False,)
print(df)


    Score Class Intervals
0     328  [300.0, 350.0)
1     470  [450.0, 500.0)
2     405  [400.0, 450.0)
3     375  [350.0, 400.0)
4     298  [250.0, 300.0)
5     326  [300.0, 350.0)
6     276  [250.0, 300.0)
7     362  [350.0, 400.0)
8     410  [400.0, 450.0)
9     255  [250.0, 300.0)
10    391  [350.0, 400.0)
11    370  [350.0, 400.0)
12    455  [450.0, 500.0)
13    229  [200.0, 250.0)
14    300  [300.0, 350.0)
15    183  [150.0, 200.0)
16    283  [250.0, 300.0)
17    366  [350.0, 400.0)
18    400  [400.0, 450.0)
19    495  [450.0, 500.0)
20    215  [200.0, 250.0)
21    157  [150.0, 200.0)
22    374  [350.0, 400.0)
23    306  [300.0, 350.0)
24    280  [250.0, 300.0)
25    409  [400.0, 450.0)
26    321  [300.0, 350.0)
27    269  [250.0, 300.0)
28    398  [350.0, 400.0)
29    200  [200.0, 250.0)


In [46]:
table2=pd.crosstab(index=df['Class Intervals'],columns='Frequency')


In [47]:
table2

col_0            Frequency
Class Intervals           
[150.0, 200.0)           2
[200.0, 250.0)           3
[250.0, 300.0)           6
[300.0, 350.0)           5
[350.0, 400.0)           7
[400.0, 450.0)           4
[450.0, 500.0)           3